version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: spendlot_postgres
    environment:
      POSTGRES_DB: spendlot
      POSTGRES_USER: spendlot_user
      POSTGRES_PASSWORD: spendlot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spendlot_network

  # Redis for caching and Celery broker
  redis:
    image: redis:7-alpine
    container_name: spendlot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - spendlot_network

  # FastAPI Application
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spendlot_api
    environment:
      - DATABASE_URL=postgresql://spendlot_user:spendlot_password@postgres:5432/spendlot
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - spendlot_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker
  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spendlot_celery_worker
    environment:
      - DATABASE_URL=postgresql://spendlot_user:spendlot_password@postgres:5432/spendlot
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - spendlot_network
    command: celery -A app.tasks.celery_app worker --loglevel=info

  # Celery Beat (Scheduler)
  celery_beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spendlot_celery_beat
    environment:
      - DATABASE_URL=postgresql://spendlot_user:spendlot_password@postgres:5432/spendlot
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
    volumes:
      - ./app:/app/app
    depends_on:
      - postgres
      - redis
    networks:
      - spendlot_network
    command: celery -A app.tasks.celery_app beat --loglevel=info

  # Flower (Celery monitoring)
  flower:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spendlot_flower
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - spendlot_network
    command: celery -A app.tasks.celery_app flower --port=5555

volumes:
  postgres_data:
  redis_data:

networks:
  spendlot_network:
    driver: bridge
